// <auto-generated />
using Customer.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customer.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Client")
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Customer.Domain.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Client 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Client 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Client 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Client 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Client 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Client 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Client 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Client 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Client 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Client 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Client 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Client 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Client 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Client 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Client 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Client 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Client 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Client 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Client 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Client 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Client 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Client 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Client 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Client 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Client 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Client 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Client 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Client 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Client 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Client 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Client 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Client 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Client 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Client 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Client 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Client 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Client 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Client 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Client 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Client 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Client 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Client 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Client 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Client 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Client 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Client 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Client 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Client 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Client 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Client 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Client 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Client 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Client 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Client 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Client 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Client 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Client 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Client 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Client 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Client 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Client 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Client 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Client 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Client 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Client 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Client 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Client 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Client 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Client 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Client 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Client 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Client 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Client 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Client 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Client 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Client 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Client 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Client 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Client 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Client 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Client 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Client 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Client 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Client 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Client 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Client 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Client 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Client 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Client 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Client 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Client 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Client 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Client 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Client 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Client 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Client 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Client 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Client 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Client 99"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Client 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
